### PR TITLE
ir: use value.Value for operands of instructions and terminators

### LINKED ISSUE #50: ir: use value.Value for operands of instructions?
This has come up in discussion and would enable APIs such as `Operands() []*value.Value`, which would allow not only use tracking, but also value replacement; as proposed by @pwaller. (ref: #42)

Depending on how far we wish to take this API change, there are some benefits and drawbacks. The main drawback I can see is if we change instructions (and terminators) to take `value.Value` instead of `*ir.BasicBlock`, since then users of the API cannot make use of the basic block directly, but would have to type assert to inspect the instructions of the basic block for instance. This is also true for the `phi` instruction, for which `Incoming` may be redefined as follows:

```diff
 // Incoming is an incoming value of a phi instruction.
 type Incoming struct {
 	// Incoming value.
 	X value.Value
 	// Predecessor basic block of the incoming value.
-	Pred *BasicBlock
+	Pred value.Value // *ir.BasicBlock
 }
```

Another instruction that would change is `catchdad`, which would take a `value.Value` instead of the concrete type `*TermCatchSwitch`:

```diff
 // InstCatchPad is an LLVM IR catchpad instruction.
 type InstCatchPad struct {
 	// Name of local variable associated with the result.
 	LocalIdent
 	// Exception scope.
- 	Scope *TermCatchSwitch
+ 	Scope value.Value // *ir.TermCatchSwitch
 	// Exception arguments.
 	Args []value.Value
 
 	// extra.
 
 	// (optional) Metadata.
 	Metadata []*metadata.MetadataAttachment
 }
```

Besides the `phi` and `catchpad` instructions, quite a few terminators would be update to make use of `value.Value` instead of `*ir.BasicBlock`.

```diff
 // TermCondBr is a conditional LLVM IR br terminator.
 type TermCondBr struct {
 	// Branching condition.
 	Cond value.Value
 	// True condition target branch.
-	TargetTrue *BasicBlock
+	TargetTrue value.Value // *ir.BasicBlock
 	// False condition target branch.
-	TargetFalse *BasicBlock
+	TargetFalse value.Value // *ir.BasicBlock
 
 	// extra.
 
 	// Successor basic blocks of the terminator.
 	Successors []*BasicBlock
 	// (optional) Metadata.
 	Metadata []*metadata.MetadataAttachment
 }
```

The `catchret` terminator would take a `value.Value` instead of `*ir.InstCatchPad`

It is also possible we'd have to update [ir.Case](https://godoc.org/github.com/llir/llvm/ir#Case) to take a `value.Value` instead of a `constant.Constant` if we want to use this approach for also refining/updating/replacing values and not just for read-only access to operands.

```diff
 // Case is a switch case.
 type Case struct {
 	// Case comparand.
-	X constant.Constant // integer constant or integer constant expression
+	X value.Value // integer constant or integer constant expression
 	// Case target branch.
 	Target *BasicBlock
 }
```

I'm currently on the fence whether this change is good or not. The data types become less exact with what values they may contain, and specifically for basic blocks, users of the API would have to type assert to access the fields specific to basic blocks (such as its instructions). On the other hand, it would enable a general and quite powerful API for operand tracking and replacement.

I'll label this for the v0.4.0 release for now, as it mostly targets data analysis and the use-def chains API.

Any input is warmly welcome.

Cheers,
/u

### PR DESCRIPTION
**Pull request by mewmew**
This PR changes the type of operands (and basic block targets) of instructions and terminators to use `value.Value` instead of their sometimes more specific type.

The benefit of this change is that it enables a very powerful operand use-tracking and operand value replacement API (see #42).
    
**Note**: this PR was initially intended for the v0.4 release. However, it could make sense to have this rather invasive API change land earlier, as otherwise we would break v0.3 uses unnecessarily.

Of course, we must first reach a consensus on whether this is the right approach to take for the API of `llir/llvm/ir`.

I have tried to consider the benefits (enables a powerful operands API) and drawbacks (less specific types of operands), and personally I think the change is worth it.

I would be very interested in getting feedback on this. And I'd also be glad to postpone this change to the v0.4 release if we need more time to discuss. As mentioned, the benefit of making this change early is that we will want to enable stability for v0.3 users, at least where we can expect future API breakage such as this one.

Fixes #50.

cc: @pwaller, @dannypsnl

P.S. I'll submit a follow-up PR to `llir/irutil` which includes a draft of what a instruction and terminator operand tracking API may look like.

Note, this change would enable the stronger operand tracking API, were we can also update those values since the operand tracking would operate on `*value.Value`. This was anticipated by @pwaller, and outlined in the following comment.

By @pwaller in https://github.com/llir/llvm/issues/42#issue-383892282
> I note that Operands() could almost return pointers to values, so that the references were mutable. However, this is broken. The only reason it is broken that I can find is the Scope field on InstCatchPad and InstCleanupPad. I think if we want to be able to obtain mutable references to Operands, those fields should become of types value.Value. I guess there are pros and cons to that. But if you want mutable references to operands I think the alternatives are going to be much uglier.

### CODE REVIEW

File: ir/helper.go [hunk 1]
```diff
@@ -335,16 +335,19 @@ type ReturnAttribute interface {
...
 // An UnwindTarget has one of the following underlying types.
 //
 //    *ir.Block
 //    ir.UnwindToCaller
 type UnwindTarget interface {
+	value.Value
 	// isUnwindTarget ensures that only unwind targets can be assigned to the
 	// ir.UnwindTarget interface.
-	isUnwindTarget()
+	//isUnwindTarget()
```
Comment (dannypsnl) [inline ir/helper.go]: Why we would need to comment out this line? If we have a good reason to remove it then just remove it I guess.

File: ir/terminator.go [hunk 2]
```diff
@@ -89,7 +89,7 @@ func (term *TermRet) LLString() string {
 // TermBr is an unconditional LLVM IR br terminator.
 type TermBr struct {
 	// Target branch.
-	Target *Block
+	Target value.Value // *ir.Block
```
Comment (dannypsnl) [inline ir/terminator.go]: I'm thinking which one would be better:

1. current solution which uses `*ir.Block` causes user can't use their own special extension on the certain case(from my understanding)
2. This PR solution solves the problem but in my view introduce another one: how can we ensure the `Target value.Value` in the case can be `*ir.Block` normally? It might be a problem when user modifying the instruction like: `termBr.Target = ...`
3. A possible way: introduce `ir.BlockInterface`(it's a bad name but points out the idea) which is `*ir.Block` in the normal case(when a user has no extend anything). And still, reserve the benefit get from 2

File: ir/terminator.go [hunk 3]
```diff
@@ -109,7 +109,7 @@ func NewBr(target *Block) *TermBr {
 func (term *TermBr) Succs() []*Block {
 	// Cache successors if not present.
 	if term.Successors == nil {
-		term.Successors = []*Block{term.Target}
+		term.Successors = []*Block{term.Target.(*Block)}
```
Comment (dannypsnl) [inline ir/terminator.go]: So, in this case, we can use `Successors []ir.BlockInterface`. At line 149 to 151:

```go
func NewCondBr(cond value.Value, targetTrue, targetFalse *Block) *TermCondBr {
	return &TermCondBr{Cond: cond, TargetTrue: targetTrue, TargetFalse: targetFalse}
}
```

A problem would be: although we help users can use `value.Value` as `TargetTrue/False`, but the function signature still denied a general type, so they have to modify the field and lose the type guarantee.

**Comment by dannypsnl** [comment]
BTW, I don't think the idea I have must be there, it's open for discussion, so I choose **comment** review.

File: ir/helper.go (hunk 1 above)
Comment (mewmew) [reply ir/helper.go]: > Why we would need to comment out this line? If we have a good reason to remove it then just remove it I guess.

I removed this now. I left it uncommented as I wasn't entirely sure how to handle the UnwindTarget sumtype. The general issue tracking how to handle sumtypes is #59.

File: ir/terminator.go (hunk 2 above)
Comment (mewmew) [reply ir/terminator.go]: > 1. current solution which uses *ir.Block causes user can't use their own special extension on the certain case(from my understanding)

Indeed. The current solution is to restrict the type of branch targets to `*ir.Block`.

> 2. This PR solution solves the problem but in my view introduce another one: how can we ensure the Target value.Value in the case can be *ir.Block normally? It might be a problem when user modifying the instruction like: termBr.Target = ...

The way to ensure that no other type than a basic block is used for branch targets is to use semantic analysis. E.g. `opt --verify`.

**Note:** that the constructors still use the restricted type, so for most users of `llir/llvm`, the `TermBr` value would be created using these constructors.

```go
// NewBr returns a new unconditional br terminator based on the given target
// basic block.
func NewBr(target *Block) *TermBr {
	return &TermBr{Target: target}
}
```

> 3. A possible way: introduce ir.BlockInterface(it's a bad name but points out the idea) which is *ir.Block in the normal case(when a user has no extend anything). And still, reserve the benefit get from 2

The main reason to use `value.Value` is to allow for a *unified* use-tracking API where we can then return, see for instance https://github.com/llir/irutil/pull/1/files#diff-d3c9f0513ce472e901fe73089a5676f2R356

```go
	case *ir.TermBr:
		return []*Use{
			{Val: &term.Target, User: term},
		}
```

The only way to return a pointer to `value.Value` (as in `Val: &term.Target`) is if `Target` is of type `value.Value`.

The benefit of returning a pointer to `value.Value` in the use-tracking API is that this allows users to *modify* the value. For instance, this could be used to replace the result of a given computation with a known value. E.g. if a compiler can prove that `%sum = add i32 32, 10` is constant, than any use of `%sum` could be replaced with the constant `i32 42`, as follows:

```go
if named, ok := (*use.Val).(value.Named); ok && named.Ident() == "%sum" {
   *use.Val = constant.NewInt(types.I32, 42)
}
```

File: ir/terminator.go (hunk 3 above)
Comment (mewmew) [reply ir/terminator.go]: > the function signature still denied a general type, so they have to modify the field and lose the type guarantee.

This is intended, as the underlying type of `Target`, `TargetTrue` and `TargetFalse` is always `*ir.Block`. The only reason we change the type to `value.Value` is to allow for the use-tracking API to take the pointer to these values (`*value.Value`).

It is not a perfect solution, but considering benefits and drawbacks, I think that the benefits outweigh the drawbacks, as using `value.Value` for operands and branch targets of instructions and terminators enable quite a powerful use-tracking API.

Having a constructor with the restricted types help ensure that users still provide a value `value.Value` type for these operands and branch targets.

File: ir/terminator.go (hunk 2 above)
Comment (dannypsnl) [reply ir/terminator.go]: Oh, I didn't explain 3 completely, the idea is `ir.BlockInterface` embed `value.Value` so it's also a kind of `value.Value`. For example:

```go
type BlockInterface interface {
  value.Value
  isBlock() bool
}
```

File: ir/terminator.go (hunk 3 above)
Comment (dannypsnl) [reply ir/terminator.go]: I rethink this part: a problem is `Successors` makes `Target` have to do type casting, which might panic at the runtime if users didn't notice this thing. Seems like it should also use `[]value.Value` type(following current PR context).

Comment (dannypsnl) [reply ir/terminator.go]: I rethink this part: a problem is `Successors` makes `Target` have to do type casting, which might panic at the runtime if users didn't notice this thing. Seems like it should also use `[]value.Value` type(following current PR context).

Comment (mewmew) [reply ir/terminator.go]: > I rethink this part: a problem is Successors makes Target have to do type casting, which might panic at the runtime if users didn't notice this thing. Seems like it should also use []value.Value type(following current PR context).

A panic at runtime is to prefer in this case as using anything other than `*ir.Block` for a branch target would result in an invalid IR. As noted above, we would then rely on semantic analysis of the IR module to report an error to the user of such invalid IR instances. And furthermore, the terminator constructors (e.g. `ir.NewBr`) already restrict the type of branch targets to `*ir.Block`, so as long as users use the constructor functions of `llir/llvm/ir`, then creating an invalid IR is made more difficult.

In essence, the idea is to have types be as specific (and restrictive) as possible where there are no other alternatives. That is the case for the parameters of e.g. `ir.NewBr` which take a `target *ir.Block` parameter. And that is also the case for `Successors` which is later used in the `Succs` method, the return type of which is `[]*ir.Block`.

I know it's not perfect, but it is a trade-off, so we can have a more general and powerful use-tracking API which operates on `*value.Value`.

File: ir/terminator.go (hunk 2 above)
Comment (mewmew) [reply ir/terminator.go]: I see, so that would restrict the input to be only basic blocks. However, taking a pointer to a `BlockInterface` and a pointer to a `value.Value` interface results in two different pointer types. As such, we could not use the `BlockInterface` for the use-tracking API, which requires `*value.Value` for each operand use it tracks.

Notably, `*ir.Block` is already a `value.Value` as it implements this interface. But we cannot take the address of a `*ir.Block` and pass it to a function that expects `*value.Value`. As such, the use-tracking API would be limited so that it could not modify the value used in an operand, it could only read the value, as we would be forced to return `[]value.Value` instead of `[]*value.Value`. The `*value.Value` requirement is further explained by @pwaller in https://github.com/llir/llvm/issues/42#issue-383892282

Comment (dannypsnl) [reply ir/terminator.go]: Ok, now I got the point; in the current context, I didn't see better ways.

**Comment by mewmew** [comment]
Thanks for the review @dannypsnl.

@pwaller, as this is an API-breaking change, and seeing as you have insight into #42, I'd be glad to have you review this PR before merging. Let me know if you are swamped during the winter holidays.

Cheers,
Robin

File: ir/helper.go (hunk 1 above)
Comment (pwaller) [reply ir/helper.go]: I still see the commented line here in the files changed view?

**Comment by mewmew** [comment]
> This looks like an improvement to me. The commented out code @dannypsnl mentions still appears there in the version shown to me in the github diff.

That's because of something we refer to as *sbs* in Swedish. It's been fixed and the issue was on me.
